In [3]:
import numpy as np

In [ ]:
arr1 = np.arange(1, 11)
print("1d array:", arr1)

1D Array: [ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
arr2 = np.random.randint(1, 21, size=(3, 3))
print(arr2)

print(np.sum(arr2))
print(np.mean(arr2))
print(np.max(arr2))



[[11 20 17]
 [18 13 20]
 [15  5  7]]
126
14.0
20


In [14]:
multi = arr2 * 2
print(multi)

[[ 8  2 24]
 [ 6 40 24]
 [28 36 26]]


In [15]:
modif = np.where(arr2 > 5, 0, arr2)
print(modif)

[[4 1 0]
 [3 0 0]
 [0 0 0]]
